### ISSUE TITLE
Display Users for admins to approve/decline

### ISSUE THREAD

**Issue by Walrussuit101** [Rithonn/ycphacks_website#16]
-allow access through edit profile page, only to admin users
-needs buttons with SQL to change isReg field

**Comment by Rithonn** [comment]
Create another panel on the bottom that will display all the users in a column form. Kind of like the schedule but a little more intricate

**Comment by Rithonn** [comment]
Have the ui looking nice for this. Going to stop and pick this back up for the final project presentation
