### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by Rithonn** [Rithonn/ycphacks_website#20]
Cleanup smaller issues that were ignored in the past presentations.

**Comment by Rithonn** [comment]
Display that a new password entered was incorrect

**Comment by Rithonn** [comment]
Make sure if a user goes to delete their account that it asks if they are sure they want to do that.

**Comment by Walrussuit101** [comment]
> Display that a new password entered was incorrect

Fixed, 5/3/19

**Comment by Walrussuit101** [comment]
> Make sure if a user goes to delete their account that it asks if they are sure they want to do that.

Fixed, 5/4/2019

**Comment by Walrussuit101** [comment]
Added better logIn error messages for user

**Comment by Rithonn** [comment]
Actually added real info to the about page

**Comment by Rithonn** [comment]
Started work on the sponsors for the front page.

**Comment by Walrussuit101** [comment]
Registration now asks for email confirmation (input twice)

**Comment by Rithonn** [comment]
Added a link to the York College campus map on the directions page.

**Comment by Rithonn** [comment]
Sponsors are now complete on the index page
