### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by Rithonn** [Rithonn/ycphacks_website#23]
Along with a confirm an account Users can also request a password reset, and receive notifications of important updates.

**Comment by Walrussuit101** [comment]
Registration email sends when a user signs up

**Comment by Walrussuit101** [comment]
Admins can now send a mass email to all accounts

**Comment by Walrussuit101** [comment]
Admins can now send a mass email to specified emails through website

**Comment by Walrussuit101** [comment]
Have website send email when an admin finishes an account's registration

**Comment by Walrussuit101** [comment]
closing, as no more methods for emailSender need to be written
